### PR TITLE
Added AsyncRead and AsyncWrite support for ProgressBar

### PR DESCRIPTION
**Pull request by x0f5c3**
Added support for tokio Read, Write and Seek traits to allow for using the ProgressBar with tokio async io traits by wrapping them in ProgressBarIter.

### CODE REVIEW

**Comment by djc** [comment]
Thanks, this seems reasonable! I'm not sure the tests are exercising anything particularly useful: `ProgressBarIter` itself does constrain the type its inner `T`, so the test doesn't really help in this case. Maybe expand the test a little to check that the `ProgressBarIter<T>` is `AsyncRead` if `T` is `AsyncRead` and similar for `AsyncWrite`?

**Comment by x0f5c3** [comment]
I think the CI job should pass now since I moved the async related uses under `#[cfg(feature = "tokio")]`

**Comment by djc** [comment]
Just a little formatting left.

**Comment by x0f5c3** [comment]
Sorry for that, forgot to run cargo fmt, should be fixed now

**Comment by djc** [comment]
Thanks!

**Pull request merged**
