### PR TITLE
Update rayon version

### PR DESCRIPTION
**Pull request by Titaniumtown**

### CODE REVIEW

**Comment by djc** [comment]
Is this actually necessary? If not there is no reason to do this, since 1.0 and 1.5 are compatible Cargo will automatically pull in rayon 1.5 whenever you build indicator.

**Comment by Titaniumtown** [comment]
I don't see any harm in it :shrug:

**Comment by djc** [comment]
We usually declare the minimum compatible version that's known to work. Bumping unnecessarily can make life harder for downstream users that rely on an older version for whatever reason.

**Comment by Titaniumtown** [comment]
Got it!

**Pull request closed without merging**
